---
title: "The Bioconductor Code of Conduct committee"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output: html_document
---

The Bioconductor Code of Conduct committee (CoCc) is responsible for developing, deseminating,
and upholding the Code of Conduct. The CoCc reports to the Bioconductor Community Advisory Board. It is currently chaired by Saskia Freytag. Membership is by invitation only, but community members are invited to contribute to via raising an issue (see below).

This meta-repository is used for general discussions of public facing materials. These include
the following:

### [Code of Conduct](./CoC_doc.html)
This is the working Code of Conduct document outlining the rules for participants of
Bioconductor community. This is a working document and may be ahead of the [official 
Code of Conduct released](http://www.bioconductor.org/about/code-of-conduct/).

### [Summary of Incident Report](./incident_response.html) 
This document summarizes the procedures of the CoCc after receival of an incident. Note that
this document is the summary of a non-public guide to incident response available only to
Bioconductor CoCc members.

### [Transparency Report](./transparency_report.html)
This document summarize the incidents that the CoCc dealt with and their resolutions.

### [Translation of the Code of Conduct](https://crowdin.com/project/bioconductor-code-of-conduct .)
The Code of Conduct has been translated by some of our members into several languages other than English. 
Note that in case of dispute [the officially released English version of the Code of Conduct](http://www.bioconductor.org/about/code-of-conduct/) supersedes. 



## Raising an issue

If you wish to address any aspects of the outlined documents or general comments, questions, or concerns regarding the procedures and processes of the Bioconductor CoCc, you are welcome to raise an [issue](https://github.com/Bioconductor/CodeOfConduct/issues). (We also encourage pull requests.) Please do not raise actual Code of Conduct violations using this venue. 

